export const MODE_NAMES = {
  competitive: "Competitive",
  unrated: "Unrated",
  deathmatch: "Deathmatch",
  spikerush: "Spike Rush",
  swiftplay: "Swiftplay",
  ggteam: "Escalation",
  hurm: "Team Deathmatch",
  premier: "Premier",
  newmap: "New Map",
  snowball: "Snowball Fight",
  onefa: "Replication",
  skirmish2v2: "Skirmish: 2v2",
  skirmishascension1v1: "Skirmish: Ascension 1v1",
  skirmishascension2v2: "Skirmish: Ascension 2v2",
  valaram: "All Random One Site",
  dodgeball: "Knockout",
  custom: "Custom",
};
