// Every localStorage key that participates in config share/export/import.
// New persistent settings must be added here or they silently won't travel.
export const CONFIG_KEYS = [
  "show_logs",
  "app_theme",
  "simplified_theme",
  "custom_theme",
  "discord_rpc",
  "start_with_windows",
  "start_minimized",
  "minimize_to_tray",
  "close_with_game",
  "disable_animations",
  "splooshima_api_key",
  "mapdodge-config",
  "auto_unqueue",
  "auto_requeue",
  "instalock_select_delay",
  "instalock_lock_delay",
  "instalock-config",
  "fake-status-config",
  "fakestatus_enabled",
  "overlay_enabled",
  "overlay_linger",
  "notifications_enabled",
  "notification_position",
  "notification_screen",
  "dodge_keybind",
  "dodge_keybind_enabled",
  "instalock-profiles",
  "instalock-active-profile",
  "dev_tab_enabled",
];
